api = "0.10"

[buildpack]
id = "fagiani/apt"
version = "0.2.5"
name = "apt Packages Buildpack"
homepage = "https://github.com/fagiani/apt-buildpack"
description = "Installs apt packages for further builds and runtime"
keywords = ["apt", "packages", "ubuntu"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-22"

[[targets]]
os = "linux"
arch = "amd64"
